class/urls.py
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name="class"
urlpatterns = [
    path('',views.home,name='home'),
    path('signup/',views.SignupView,name='signup'),
    path('signin/',views.SigninView,name='signin'),
    path('signout/',views.signoutView,name='signout'),
    path('home/', views.homeView, name="home"),
    path('create_class/',views.create_class,name="create"),
    path('join_class/',views.join_class,name="join"),
    path('class/<int:cid>',views.classView, name="classview"),
    path('pdf/<int:Mid>', views.pdfview, name="pdfView"),
    path('material/<int:Mid>', views.materialview, name="materialView"),
    path('send/',views.sendanmail,name="sendmail"),
    path('invite/',views.invite,name="invite"),
    path('review/<int:mid>',views.review,name="review"),
    path('reviewStudent/<int:rid>',views.reviewstudent,name="reviewstudent"),
    path('api/', views.apiView, name="api"),
    path('api/student/<str:pk>', views.studentlist, name="studentlist"),

    path('api/material-list/', views.materiallist, name="material-list"),
    path('api/material-post/', views.materialpost, name="material-post"),
    path('api/signIn/', views.signinInfo, name="sign-info"),
    path('api/register/', views.register, name="register"),
    path('api/join/', views.joinClass, name="Join"),
    path('api/createClass/', views.createClass, name="createclass"),
    path('api/classList/', views.Classlist, name="classList"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/urls.py
from classroom.settings import EMAIL_BACKEND
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('class.urls',namespace="class")),


]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <title>Classroom</title>
      <style>
          .bg-custom-1 {
  background-color: #85144b;
}
body{
    font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
@media only screen and (max-width: 578px) {
.navbar-nav{
background-color:#F0F8FF;
margin-left:auto;
}

}
.bg-custom-2 {
background-image: linear-gradient(15deg, #13547a 0%, #80d0c7 100%);
}
.div4:hover{
 background: rgba(76, 175, 80, 0.3)
}
.card:hover{
box-shadow: 0 0 10px 0 rgba(100, 100, 100, 0.26);
}
      </style>
  </head>
  <body>
   <nav class="navbar navbar-light bg-white fixed-top navbar-expand-sm"style="border-bottom: 1px solid lightgrey;height:57px">
  <a class="navbar-brand" href="#" style="color:green">

    Classroom
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
       <div class="collapse navbar-collapse justify-content-end" id="navbar-list-4">


    {% if request.session.teacher_id or request.session.student_id %}
    <ul class="navbar-nav">
         <li class="nav-item dropdown ">
        <a class="nav-link active" style="margin-top:8px" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-plus fa-lg" ></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          {% if request.session.teacher_id %}
          <a class="dropdown-item"  type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" href="#">Create Class</a>
          {% else %}
          <a class="dropdown-item" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal1" href="#">Join Class</a>
          {% endif %}
        </div>
      </li>

        <li class="nav-item dropdown">
          {%if profile.image %}
        <a class="nav-link active" href="#" id="navbarDropdownMenuLink1" role="button" id="pic" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

          <img src="{{profile.image.url}}" width="40" height="40" class="rounded-circle">
        {{ request.session.name2 }}
        </a>
          {%endif%}
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink1">
          <a class="dropdown-item" href="#">Edit Profile</a>
          <a class="dropdown-item" href="{% url 'class:signout' %}">Sign Out</a>
        </div>
      </li>
    </ul>
        {% endif %}
       </div>

</nav>
   <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create class</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'class:create' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="class-name" class="col-form-label">Class name:</label>
            <input type="text" name="class_name" class="form-control" id="class-name">
          </div>
          <div class="form-group">
            <label for="section" class="col-form-label">Section:</label>
            <input type="text" name="sec" class="form-control" id="section">
          </div>
          <div class="form-group">
            <label for="subject" class="col-form-label">Subject:</label>
            <input type="text"  name="sub" class="form-control" id="subject">
          </div>
            <div class="form-group">
            <label for="room" class="col-form-label">Room:</label>
            <input type="text" name="room" class="form-control" id="room">
          </div>
                <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Create</button>
      </div>
        </form>
      </div>

    </div>
  </div>
</div>

     <div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel1">Join class</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'class:join' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="class-code" class="col-form-label">Class code:</label>
            <input type="text" name="class_code" class="form-control" id="class-code">
          </div>

                <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Join</button>
      </div>
        </form>
      </div>

    </div>
  </div>
</div>
{% block body %}
   {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/base2.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <title>{{detail.name}}</title>
      <style>


.nav-item1 a:hover {
  color:#137333;
  border-bottom: 3px solid #137333;
}
.nav-item1 a.active {
color:#137333;
  border-bottom: 3px solid #137333;
}
.nav-item1 a {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  border-bottom: 3px solid transparent;
}
.bg-custom-1 {
  background-color: #85144b;
}
@media only screen and (max-width: 578px) {
.navbar-nav{
background-color:#F0F8FF;
margin-left:auto;
}
}
.bg-custom-2 {
background-image: linear-gradient(15deg, #13547a 0%, #80d0c7 100%);
}
*{
    font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
      </style>
  </head>
  <body>
   <nav class="navbar navbar-light bg-white fixed-top navbar-expand-sm" style="border-bottom: 1px solid lightgrey;height:57px">
  <a class="navbar-brand" href="#">

    {{detail.name}}
  </a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
       <div class="collapse navbar-collapse justify-content-end" id="navbar-list-4">

<ul class="navbar-nav mx-auto item">
  <li class="nav-item1">
    <a class="active" href="#st" id="stream">Stream</a>
  </li>
  <li class="nav-item1">
    <a  href="#mat" id="material">Material</a>
  </li>
  <li class="nav-item1">
    <a  href="#p" id="people">People</a>
  </li>
</ul>


    <ul class="navbar-nav">


        <li class="nav-item dropdown">
            {%if profile.image %}
        <a class="nav-link active" href="#" id="navbarDropdownMenuLink1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img src="{{profile.image.url}}" width="40" height="40" class="rounded-circle">
        {{ request.session.name2 }}
        </a>
            {%endif%}
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink1">

          <a class="dropdown-item" href="#">Edit Profile</a>
          <a class="dropdown-item" href="{% url 'class:signout' %}">Sign Out</a>
        </div>
      </li>
    </ul>

       </div>

</nav>
{% block body %}
   {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
<script></script>
</html>

templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    <h1> 
        SAND AN EMAIL
    </h1>
    <form action="{% url 'class:sendmail' %} " method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td>
                    TO
                </td>
                <td>
                    <input type="email" name="toemail">
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <textarea name="content"  cols="30" rows="10"></textarea>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="send">
                </td>
            <td>
                <input type="reset" value="clean">
            </td>
            </tr>
        </table>
    </form>
</body>
</html>
<style>
	body {
		color: #fff;
		background: #63738a;
		font-family: 'Roboto', sans-serif;
	}
    .form-control{
		height: 40px;
		box-shadow: 0 1px 2px 0 rgb(60 64 67 / 30%), 0 2px 6px 2px rgb(60 64 67 / 15%);
		color: #969fa4;
	}
	.form-control:focus{
		border-color: #5cb85c;
	}
    .form-control, .btn{
        border-radius: 3px;
    }
	
</style>

templates/invitation_send.html
<h1>
    invitation has been send
</h1>

templates/material.html
{% extends 'base2.html' %}

{% block body %}
<html>
<head>
<style>
.div2 {
    margin: auto;
  width: 800px;

  margin-top: 60px;

}
.work{

  width: 310px;
  height: auto;
  border-radius:10px;

  border: 1px solid white;
  box-shadow: 0 1px 2px 0 rgb(60 64 67 / 30%), 0 2px 6px 2px rgb(60 64 67 / 15%);
}
    </style>
</head>
<body>
<div class="div2">
<h3 id="title" style="color:green">{{ material.title }}</h3>
    <p style="font-size:13px">{{material.classId.teacherId.Fname}} {{material.classId.teacherId.Lname}}--{{material.created_at}}
        <span style="float:right;font-size:15px;margin-top:10px">Due {{material.dueTime}}</span></p>
    <hr style="background-color:green">
    <p>{{material.description}}</p>
     <a href="{{ material.get_absolute_url }}" target=”_blank” style="color:green;text-decoration:none">{{material.file}}
     </a>
    <hr style="background-color:green">
     {% if request.session.teacher_id%}
    <a type="button" href="{{material.get_absolute_url_reviewmaterial}}" class="btn btn-success">Review</a>
    {%else%}
<div class="work">
    <h5>Your Work</h5>
    {%if work.comTime%}
    <p>Completed on: <strong>{{work.comTime}}</strong></p>
    <p>Reading time: <strong>{{readingtime}} minutes</strong></p>
    {%else%}
    <P>Incomplete</P>
    {%endif%}
</div>
    {% endif %}
</div>
</body>
<script>
    document.querySelector(".item").style.display="none"
    document.querySelector(".navbar-brand").innerHTML="{{material.classId.name}}";
</script>
</html>
{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% block body %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <title>Classroom Sign In</title>
      <style>
body {
    background-color:

}

.card {
    width: 400px;
    border: 1px solid white;
     box-shadow: 0 1px 2px 0 rgb(60 64 67 / 30%), 0 2px 6px 2px rgb(60 64 67 / 15%);
     margin-top:100px;
}

.btr {
    border-top-right-radius: 5px !important
}

.btl {
    border-top-left-radius: 5px !important
}

.btn-dark {
    color: #fff;
    background-color: #0d6efd;
    border-color: #0d6efd
}

.btn-dark:hover {
    color: #fff;
    background-color: #0d6efd;
    border-color: #0d6efd
}

.nav-pills {
    display: table !important;
    width: 100%
}

.nav-pills .nav-link {
    border-radius: 0px;
    border-bottom: 1px solid #0d6efd40
}

.nav-item {
    display: table-cell;
    background: #0d6efd2e
}

.form {
    padding: 10px;
    height: 300px
}

.form input {
    margin-bottom: 12px;
    border-radius: 3px
}

.form input:focus {
    box-shadow: none
}

.form button {
    margin-top: 30px
}
      </style>
  </head>
  <body>
<div class="d-flex justify-content-center align-items-center mt-5">
    <div class="card">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item text-center"> <a class="nav-link active btl" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Teacher</a> </li>
            <li class="nav-item text-center"> <a class="nav-link btr" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Student</a> </li>
        </ul>
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                                   {% for message in messages%}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
                <div class="form px-4 pt-5">

                     <form action="{% url 'class:signin' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="Email" class="form-control" placeholder="Email">
                         <input type="password" name="Password" class="form-control" placeholder="Password">
                          <input name="isStudent" type="hidden" value="false">
                         <button type="submit"class="btn btn-dark btn-block">Sign In as teacher</button>
                         </form>
                       		<div class="d-flex justify-content-center links" style="margin-top:20px">
						Don't have an account? <a href="{% url 'class:signup' %}" style="text-decoration: none;" class="ml-2">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center links">
						<a href="{% url 'class:signup' %}"style="text-decoration: none;">Forgot your password?</a>
					</div>
                </div>

            </div>
            <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                                                   {% for message in messages%}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
               <div class="form px-4 pt-5">
                   <form action="{% url 'class:signin' %}" method="POST">
                    {% csrf_token %}
                   <input type="text" name="Email" class="form-control" placeholder="Email">
                   <input type="password" name="Password" class="form-control" placeholder="Password">
                       <input name="isStudent" type="hidden" value="true">
                   <button type="submit" class="btn btn-dark btn-block">Sign In as student</button>
               </form>

                   		<div class="d-flex justify-content-center links" style="margin-top:20px">
						Don't have an account? <a href="{% url 'class:signup' %}" style="text-decoration: none;" class="ml-2">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center links">
						<a href="{% url 'class:signup' %}"style="text-decoration: none;">Forgot your password?</a>
					</div>
               </div>
            </div>
        </div>
    </div>
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
<title>Sign Up</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
	body {
		color: #fff;
		background: #63738a;
    font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;

	}
    .form-control{
		height: 40px;
		box-shadow: 0 1px 2px 0 rgb(60 64 67 / 30%), 0 2px 6px 2px rgb(60 64 67 / 15%);
		color: #969fa4;
	}
	.form-control:focus{
		border-color: #5cb85c;
	}
    .form-control, .btn{
        border-radius: 3px;
    }
	.signup-form{
		width: 400px;
		margin: 0 auto;
		padding: 30px 0;
	}
	.signup-form h2{
		color: #636363;
        margin: 0 0 15px;
		position: relative;
		text-align: center;
    }
	.signup-form h2:before, .signup-form h2:after{
		content: "";
		height: 2px;
		width: 30%;
		background: #d4d4d4;
		position: absolute;
		top: 50%;
		z-index: 2;
	}
	.signup-form h2:before{
		left: 0;
	}
	.signup-form h2:after{
		right: 0;
	}
    .signup-form .hint-text{
		color: #999;
		margin-bottom: 30px;
		text-align: center;
	}
    .signup-form form{
		color: #999;
		border-radius: 3px;
    	margin-bottom: 15px;
        background: #f2f3f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
	.signup-form .form-group{
		margin-bottom: 20px;
	}
	.signup-form input[type="checkbox"]{
		margin-top: 3px;
	}
	.signup-form .btn{
        font-size: 16px;
        font-weight: bold;
		min-width: 140px;
        outline: none !important;
    }
	.signup-form .row div:first-child{
		padding-right: 10px;
	}
	.signup-form .row div:last-child{
		padding-left: 10px;
	}
    .signup-form a{
		color: #fff;
		text-decoration: underline;
	}
    .signup-form a:hover{
		text-decoration: none;
	}
	.signup-form form a{
		color: #0d6efd;
		text-decoration: none;
	}
	.signup-form form a:hover{
		text-decoration: underline;
	}
</style>
</head>
<body>
<div class="signup-form" style="margin-top:-30px">

    <form action="{% url 'class:signup' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
		<h2>Sign Up</h2>
        {% for message in messages%}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
		<p class="hint-text">Create your account. It's free and only takes a minute.</p>
        <div class="form-group">
			<div class="row">
				<div class="col-xs-6"><input type="text" class="form-control" name="Fname" placeholder="First Name" required="required"></div>
				<div class="col-xs-6"><input type="text" class="form-control" name="Lname" placeholder="Last Name" required="required"></div>
			</div>
        </div>
        <div class="form-group">
        	<input type="email" class="form-control" name="Email" placeholder="Email" required="required">
        </div>
        <div class="form-group">
        <label for="account">Account Type:</label>
<select id="account" name="AccountType">
  <option value="teacher">Teacher</option>
  <option value="student">Student</option>
</select>
        </div>
        		<div class="form-group">
                    <label for="image">Profile Picture:</label>
            <input type="file"  id="image" name="image" placeholder="Profile Picture" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" name="Password" placeholder="Password" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password" required="required">
        </div>
        <div class="form-group">
			<label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a></label>
		</div>
		<div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg btn-block">Sign Up Now</button>
        </div>
    </form>
	<div class="text-center">Already have an account? <a href="{% url 'class:signin' %}">Sign in</a></div>
</div>
</body>
</html>
{% endblock %}